app:
  name: 'go-clean-templat'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'go-clean-template'

postgres:
  pool_max: 2
  url : 'postgres://postgres:postgres@localhost:5432/postgres'

jwt:
  secret_key: 'superSecretKey'
  access_token_ttl: 900
  refresh_token_ttl: 3600

grpcServer:
  port: ":9090"
